name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: "16.13.2"
      - run: |
          npm ci
          npm run build
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_app_build: true
          app_location: "/dist"
          action: "upload"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_TOKEN }}
